CREATE DATABASE human_friends;

USE human_friends;

CREATE TABLE dogs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PET_ANIMAL',
    view VARCHAR(20) NOT NULL DEFAULT 'DOG',
    name VARCHAR(20) NOT NULL,
    birthdate DATE NOT NULL,
    commands VARCHAR(230)
);

CREATE TABLE cats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PET_ANIMAL',
    view VARCHAR(20) NOT NULL DEFAULT 'CAT',
    name VARCHAR(20) NOT NULL,
    birthdate DATE NOT NULL,
    commands VARCHAR(230)
);

CREATE TABLE hamsters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PET_ANIMAL',
    view VARCHAR(20) NOT NULL DEFAULT 'HAMSTER',
    name VARCHAR(20) NOT NULL,
    birthdate DATE NOT NULL,
    commands VARCHAR(230)
);

CREATE TABLE horses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PACK_ANIMAL',
    view VARCHAR(20) NOT NULL DEFAULT 'HOURSE',
    name VARCHAR(20) NOT NULL,
    birthdate DATE NOT NULL,
    commands VARCHAR(230)
);

CREATE TABLE camels (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PACK_ANIMAL',
    view VARCHAR(20) NOT NULL DEFAULT 'CAMEL',
    name VARCHAR(20) NOT NULL,
    birthdate DATE NOT NULL,
    commands VARCHAR(230)
);

CREATE TABLE donkeys (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PACK_ANIMAL',
    view VARCHAR(20) NOT NULL DEFAULT 'DUNKEY',
    name VARCHAR(20) NOT NULL,
    birthdate DATE NOT NULL,
    commands VARCHAR(230)
);